import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { FormsModule } from '@angular/forms';

interface Recipe {
  name: string;
  product: string;
  speed: number;
  description: string;
  lastUpdate: string;
  steelGrade: string;
  active: boolean;
}

@Component({
  selector: 'app-recipe',
  standalone: true,
  imports: [
    CommonModule,
    TableModule,
    ButtonModule,
    InputTextModule,
    FormsModule
  ],
  templateUrl: './recipeNew.component.html',
  styleUrl: './recipeNew.component.scss'
})
export class RecipeNewComponent implements OnInit {
  standDetails: any[] = [];
  selectedRecipe: Recipe | null = null;
  globalFilter: string = '';

  ngOnInit() {
    this.loadRecipes();
  }

  loadRecipes() {
    this.standDetails = [
      {
        device: 'Stand1',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand2',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand3',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand4',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand5',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand6',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand7',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand8',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand9',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand10',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand11',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand12',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand13',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand14',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand15',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand16',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand17',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand18',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand19',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand20',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      },
      {
        device: 'Stand21',
        enable: true,
        diameter: 11.02,
        groove: 4.5,
        gearRatio: 1.5,
        speedRpm: 11.02,
        Rfactor: 1.02,
        tensionRegulationEnable: true,
        tensionReference: 100,
        looperRegulationEnable: true,
        looperReference: 100,
        looperPropGain: 100,
        looperArmUpDelay: 100,
        looperArmDNDelay: 100,
        deltaVHeadEnable: true,
        deltaVHeadReference: 100,
        deltaVDelayDrop: 100,
        deltaVDelayRaise: 100,
        deltaVRampRaise: 100,
        deltaVRampDrop: 100,
        deltaVTailEnable: true,
        deltaVTailReference: 100,
        deltaVTailDelayDrop: 100,
        deltaVTailDelayRaise: 100,
        deltaVTailRampRaise: 100,
        deltaVTailRampDrop: 100,       
      }      
    ];
  }

  onRowSelect(event: any) {
    this.selectedRecipe = event.data;
  }

  onRowUnselect(event: any) {
    this.selectedRecipe = null;
  }

  downloadRecipe() {
    console.log('Download recipe');
  }

  uploadRecipe() {
    console.log('Upload recipe');
  }

  copyRecipe() {
    console.log('Copy recipe');
  }

  addRecipe() {
    console.log('Add new recipe');
  }

  editRecipe() {
    if (this.selectedRecipe) {
      console.log('Edit recipe:', this.selectedRecipe);
    }
  }

  deleteRecipe() {
    if (this.selectedRecipe) {
      console.log('Delete recipe:', this.selectedRecipe);
    }
  }

  getActiveStatus(active: boolean): string {
    return active ? '✓' : '—';
  }
}
